name: 🐞 Bug report
description: Create a bug report to help us improve AdGuard Browser Extension
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please answer the following questions for yourself before submitting an issue. 
        **YOU MAY DELETE THE PREREQUISITES SECTION.**
      options:
        - label: I am running the latest version
          # TODO: адаптировать этот блок ... 

- type: input
    id: version
    attributes:
      label: AdGuard version
      description: What version of our software are you running?
      placeholder: for example, 4.1.22 beta
    validations:
      required: true

- type: input
    id: version
    attributes:
      label: Browser version
      description: What browser do you use?
      placeholder: for example, Chrome 106
    validations:
      required: true

- type: input
    id: version
    attributes:
      label: OS version
      description: What operating system do you use?
      placeholder: for example, macOS 12.4 
    validations:
      required: true

 - type: dropdown
    id: filters
    attributes:
      label: What filters do you have enabled?
      description: Select enabled filters from the list or enter URLs of any custom filters in the comment field below.
      multiple: true
      options:
        - AdGuard Base filter
        - AdGuard Mobile Ads filter
        - AdGuard Chinese filter
        - AdGuard Dutch filter
        - AdGuard French filter
        - AdGuard German filter
        - AdGuard Japanese filter
        - AdGuard Russian filter
        - AdGuard Spanish/Portuguese filter
        - AdGuard Turkish filter
        - AdGuard Tracking Protection filter
        - AdGuard URL Tracking filter
        - AdGuard Social Media filter
        - AdGuard Annoyances filter
        - AdGuard DNS filter
        - AdGuard Experimental filter
        - Filter unblocking search ads and self-promotion
        - ---Third-party filters---
        - EasyList
        - ABPindo
        - Bulgarian list
        - EasyList China
        - EasyList Czech and Slovak
        - EasyList Dutch
        - EasyList Germany
        - EasyList Hebrew
        - EasyList Italy
        - EasyList Lithuania
        - Latvian List
        - Liste AR
        - Liste FR
        - ROList
        - EasyPrivacy
        - Icelandic ABP List
        - AdBlockID
        - Greek AdBlock Filter
        - Fanboy's Annoyances
        - Fanboy's Social Blocking List
        - Web Annoyances Ultralist
        - Thai Ads Filters
        - Hungarian filter
        - Peter Lowe's Blocklist
        - Xfiles
        - Adblock Warning Removal List
        - Online Malicious URL Blocklist
        - Spam404
        - RU AdList - Counters
        - ABPVN List
        - Fanboy's Enhanced Tracking List
        - Official Polish filters for AdBlock, uBlock Origin & AdGuard
        - Polish GDPR-Cookies Filters
        - Estonian List
        - ChinaList+EasyList
        - CJX's Annoyances List
        - Polish Social Filters
        - Adblock-Persian list
        - Fanboy's Swedish
        - Fanboy's Anti-Facebook List
        - Fanboy's Vietnamese
        - List-KR
        - xinggsf
        - I don't care about cookies
        - Fanboy's Spanish\/Portuguese
        - EasyList Spanish
        - KAD - Anti-Scam
        - Adblock List for Finland
        - ROLIST2
        - Iranian filter
        - road-block
        - Polish Annoyances Filters
        - Polish Anti Adblock Filters
        - Fanboy's Anti-thirdparty Fonts
        - BarbBlock
        - EasyList Cookie List
        - NoCoin Filter List
        - Frellwit's Swedish Filter
        - YousList
        - AlleBlock
        - EasyList Polish
        - Polish Anti-Annoying Special Supplement
        - Dandelion Sprout's Nordic Filters
        - Dandelion Sprout's Annoyances List
        - Legitimate URL Shortener
    validations:
      required: true

  - type: dropdown
    id: stealth
    attributes:
      label: What Stealth Mode options do you have enabled?
      description: Select any of these options if you have them enabled in Stealth Mode
      multiple: true
      options:
        - Hide your search queries
        - Send Do-Not-Track signals
        - Self-destruction of third-party cookies
        - Self-destruction of first-party cookies
        - Disable cache for third-party requests
        - Block third-party Authorization header
        - Block WebRTC
        - Block Push API
        - Block Location API
        - Hide Referrer from third-parties (specify in comment below, if used custom value)
        - Hide your User-Agent (specify in comment below, if used custom value)
        - Mask your IP address (specify in comment below, if used custom value)
        - Remove X-Client-Data header from HTTP requests
        - Protect from DPI

  - type: textarea
    id: comments
    attributes:
      label: Add your comment and screenshots
      description: |
        1. Add screenshots of the problem. You can drag and drop images or paste them from clipboard;
           Use `<details> </details>` tag to hide screenshots under the spoiler; 
        2. Describe the issue extensively unless it is absolutely clear from the screenshot what the problem is;
        You can also indicate any other information that you think the developers should know.

        Warning: Please remove personal information before uploading screenshots!
      values: |
          ### Issue Details

          <!--- Please include all relevant details about the environment you experienced the bug in -->

          ### Expected Behavior

          <!-- A clear and concise description of what you expected to happen. -->


          ### Screenshots

          <!-- If applicable, add screenshots to help explain your problem. -->

          <details><summary>Screenshot:</summary>

          <!--- drag and drop, upload or paste your screenshot to this area-->

          </details>

          ### Additional Information

          <!-- Add any other context about the problem here. -->
      value: |
          1. <comment>

          2. Screenshots
          <details><summary>Screenshot 1:</summary>

          <!-- paste screenshot here -->

          </details>

          <details><summary>Screenshot N:</summary>

          <!-- paste screenshot here -->

          </details>
    validations:
      required: true
  